# Build and deploy DocC to GitHub pages. Based off of @karwa's work here:
# https://github.com/karwa/swift-url/blob/main/.github/workflows/docs.yml
name: Documentation

on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name : Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2

      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs-out

      - name: Build documentation
        run: >
          rm -rf docs-out/.git;
          rm -rf docs-out/main;

          for tag in $(echo "main"; git tag);
          do
              echo "⏳ Generating documentation for "$tag" release.";

              if [ -d "docs-out/$tag" ] 
              then 
                  echo "✅ Documentation for "$tag" already exists.";
              else 
                  git checkout "$tag";

                  rm -rf .build;

                  mkdir -p "docs-out/$tag";

                  xcodebuild docbuild -scheme UIEnvironment \
                      -destination generic/platform=iOS \
                      OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs-out/$tag --hosting-base-path /UIEnvironment/$tag" \
                      && echo "✅ Documentation generated for "$tag" release." \
                      || echo "⚠️ Documentation skipped for "$tag".";
              fi;
          done

      - name: Fix permissions
        run: 'sudo chown -R $USER docs-out'
      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true